apiVersion: batch/v1
kind: Job
metadata:
  name: check-pipeline
spec:
  template:
    metadata:
      name: check-pipeline
    spec:
      containers:
        - command:
            - '/bin/sh'
            - '-c'
            - >
              echo 'SPINNAKER_CONFIG_JSON={"test": 123}'
          image: alpine
          name: check-pipeline
      restartPolicy: Never
