apiVersion: batch/v1
kind: Job
metadata:
  name: check-pipeline
spec:
  template:
    metadata:
      name: check-pipeline
    spec:
      containers:
        - command:
            - '/bin/sh'
            - '-c'
            - >
              touch test.yaml; echo 'test: 123' > test.yaml; content=$(cat test.yaml | base64 | tr -d \\n); echo "SPINNAKER_CONFIG_JSON={\"artifacts\": [{ \"type\":\"embedded/base64\",\"name\": \"job_generated_artifact\", \"reference\": \"${content}\"}]}"
          image: alpine
          name: check-pipeline
      restartPolicy: Never
