apiVersion: batch/v1
kind: Job
metadata:
  name: check-pipeline
spec:
  template:
    metadata:
      name: check-pipeline
    spec:
      containers:
        - command:
            - '/bin/sh'
            - '-c'
            - >
              apk add git; apk add ansible; git clone https://github.com/DolorDeus/spinnaker.git; touch test.yaml; echo 'kind: ConfigMap' > test.yaml; echo 'apiVersion: v1' >> test.yaml; echo 'metadata:' >> test.yaml; echo '  name: example-configmap' >> test.yaml; echo 'data:' >> test.yaml; echo '  database: ${ parameters.dbtype }' >> test.yaml; echo '  testansyaml: "{{ yamltestkey }}"' >> test.yaml; echo '  testansjson: "{{ jsontestkey }}"' >> test.yaml; ansible localhost -m template -a 'src=spinnaker/test.yaml dest=spinnaker/test.yaml' -e @values.json -e @values.yaml; content=$(cat test.yaml | base64 | tr -d \\n); echo "SPINNAKER_CONFIG_JSON={\"artifacts\": [{\"type\":\"embedded/base64\", \"name\": \"job_generated_artifact\", \"reference\": \"${content}\"}]}"
          image: huecker.io/library/alpine:latest
          name: check-pipeline
      restartPolicy: Never
