apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  labels:
    run: {{ .Values.app_name }}
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: {{ .Values.app_name }}
